name: Build Artifacts

on:
  workflow_run:
    workflows: ["Check Upstream"]
    branches: [master]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32, x64]
      fail-fast: false

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone upstream full
        run: |
          git clone https://github.com/zrax/pycdc.git upstream

      - name: Configure and Build ${{ matrix.platform }}
        working-directory: upstream
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A ${{ matrix.platform }} -DCMAKE_CONFIGURATION_TYPES="Release" ..
          cmake --build . --config Release

      - name: Package Release Artifact
        working-directory: upstream/build/Release
        run: |
          Compress-Archive -Path *.exe -DestinationPath ../../pycdc-release-${{ matrix.platform }}.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pycdc-release-${{ matrix.platform }}
          path: upstream/pycdc-release-${{ matrix.platform }}.zip
