name: Check Upstream

on:
  schedule:
    - cron: '0 0 1,16 * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  UPSTREAM_URL: https://github.com/zrax/pycdc.git
  HASH_FILE: last-hash.txt

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read last known hash
        id: readhash
        run: |
          if [[ -f "$HASH_FILE" ]]; then
            echo "last_hash=$(cat $HASH_FILE)" >> $GITHUB_OUTPUT
          else
            echo "last_hash=" >> $GITHUB_OUTPUT
          fi

      - name: Clone upstream shallow
        id: clone
        run: |
          git clone --no-checkout $UPSTREAM_URL upstream
          cd upstream
          git fetch --depth=1 origin master
          git checkout FETCH_HEAD
          echo "new_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Compare hashes
        id: compare
        run: |
          if [[ "${{ steps.clone.outputs.new_hash }}" != "${{ steps.readhash.outputs.last_hash }}" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update last-hash.txt and push
        if: steps.compare.outputs.changed == 'true'
        run: |
          echo "${{ steps.clone.outputs.new_hash }}" > $HASH_FILE
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add $HASH_FILE
          git commit -m "Update last-hash to ${{ steps.clone.outputs.new_hash }}"
          git push origin master
        shell: bash
