name: MSVC-CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir build
        
      - name: Configure CMake
        working-directory: build
        run: cmake .. -G "Visual Studio 17 2022" -A Win32 -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        working-directory: build
        run: cmake --build . --config Debug

      - name: Run Custom Bash Tests
        working-directory: build/Debug
        run: bash.exe ..\..\tests\all_tests.sh
        env:
          PYTHON_EXE: python.exe
          JOBS: 4

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pycdc-release
          path: build\Release\*.exe
